<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="0.082" timestamp="2022-11-28T11:59:42.372469" hostname="BAN-LAP-VREDDY"><testcase classname="test_multi_11" name="test_multiplication_11[1-11]" time="0.002" /><testcase classname="test_multi_11" name="test_multiplication_11[2-22]" time="0.001" /><testcase classname="test_multi_11" name="test_multiplication_11[3-35]" time="0.001"><failure message="assert (11 * 3) == 35">num = 3, output = 35

    @pytest.mark.parametrize("num, output",[(1,11),(2,22),(3,35),(4,44)])
    def test_multiplication_11(num, output):
&gt;      assert 11*num == output
E      assert (11 * 3) == 35

test_multi_11.py:5: AssertionError</failure></testcase><testcase classname="test_multi_11" name="test_multiplication_11[4-44]" time="0.001" /></testsuite></testsuites>